### ISSUE TITLE
Newest Ripper Fails in Docker Container

### ISSUE THREAD

**Issue by jmdelahanty** [Tyelab/bruker_pipeline#30]
The newest Prairie View ripper seems to fail finding a specific `.dll` called `VCRUNTIME140_1.dll`. From looking online [like [here](https://answers.microsoft.com/en-us/windows/forum/all/vcruntime1401dll-missing/f4178975-f2d9-4fac-be5b-97e5a31a08c0)] this is something that the `vcrun2015` command within the build instructions should handle and must have handled previously. I just attempted to use a different `vcrun` command with 2017 instead of 2015, but that also failed with the same problem. Here's the output of the terminal when running beyblade:

```
(beyblade) jdelahanty@cheetos:/snlkt/data/bruker_pipeline$ ./beyblade.sh
Starting container for: LHE060-plane1-20221013-SNLKT-ripper
(beyblade) jdelahanty@cheetos:/snlkt/data/bruker_pipeline$ WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
000d:err:menubuilder:init_xdg error looking up the desktop directory
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
0031:err:module:import_dll Library VCRUNTIME140_1.dll (which is needed by L"Z:\\apps\\prairie_view\\5.7.64.200\\daq_int.dll") not found
```

I'm going to see if using a more up to date version of winetricks solves this issue. For now, data is being copied to specialk (the computer upstairs) and the ripper can be run locally there and transferred back to the server until this is solved.

**Comment by jmdelahanty** [comment]
The newest version of `docker-wine` works and provides the normal `warnme`/`fixme` messages until it fails to create a file for some reason... looking into this now.

```
(beyblade) jdelahanty@cheetos:/snlkt/data/bruker_pipeline$ ./beyblade.sh
Starting container for: LHE060-plane1-20221013-SNLKT-ripper
(beyblade) jdelahanty@cheetos:/snlkt/data/bruker_pipeline$ WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
0034:fixme:ver:GetCurrentPackageId (000000000069FD70 0000000000000000): stub
00c4:fixme:imm:ImeSetActiveContext (0x3ea50, 0): stub
00c4:fixme:imm:ImmReleaseContext (0000000000010020, 000000000003EA50): stub
002c:fixme:imm:ImeSetActiveContext (0x40ab0, 1): stub
002c:fixme:imm:ImmReleaseContext (000000000001004E, 0000000000040AB0): stub
00bc:fixme:ver:GetCurrentPackageId (000000000062FD70 0000000000000000): stub
0120:err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\ucrtbase.dll" (error=80)
0128:fixme:ver:GetCurrentPackageId (000000000062FD70 0000000000000000): stub
0120:fixme:ver:GetCurrentPackageId (000000000062FD70 0000000000000000): stub
0134:err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\ucrtbase.dll" (error=80)
013c:fixme:ver:GetCurrentPackageId (0062FEA4 00000000): stub
0134:fixme:ver:GetCurrentPackageId (0062FEA4 00000000): stub
Traceback (most recent call last):
  File "/apps/rip.py", line 475, in <module>
    raw_to_tiff(args.directory, args.ripper_version, args.num_images)
  File "/apps/rip.py", line 231, in raw_to_tiff
    behavior_csv = [file for file in behavior_glob][0]
IndexError: list index out of range
X connection to :100 broken (explicit kill or server shutdown).
X connection to :100 broken (explicit kill or server shutdown).
X connection to :100 broken (explicit kill or server shutdown).
```

**Comment by jmdelahanty** [comment]
Fixed, pushing update in a couple minutes...

**Comment by jmdelahanty** [comment]
This message tipped me off to the error:

```
Traceback (most recent call last):
  File "/apps/rip.py", line 475, in <module>
    raw_to_tiff(args.directory, args.ripper_version, args.num_images)
  File "/apps/rip.py", line 231, in raw_to_tiff
    behavior_csv = [file for file in behavior_glob][0]
IndexError: list index out of range
```

Since the newest version of the ripper required rebuilding the image and using a more modern version of winetricks for some reason, the error/fixme messages that came out were different and had things take longer to start than before. This means that the polling for the csv file that's generated needed to be delayed further from 10 to 20 seconds so the ripper had time to properly get started.
